media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date, tags ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
  - name: test
    label: test page
    type: file
    path: src/pages/test.json
    fields:
      - name: authors
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: body, label: About text, type: rich-text }
      - { name: heroVideo, label: Hero video, type: file, options: { input: public/assets, output: /assets } }
      - { name: vimeoLinks, label: Vimeo links, type: object, list: true, fields: [ { name: vimeoLink, label: Vimeo link, type: string }, { name: vimeoTitle, label: Vimeo title, type: string } ] }
      - { name: instaLink, label: Instagram Link, type: string }
      - { name: phone, label: Phone Number, type: string }
      
  - name: shares
    label: Share Pages
    type: collection
    path: src/_data/share
    format: json
    filename:
      template: "{primary}.json"
      field: true
    view:
      fields: [ title, collection, comments, eventdate, date ]
      primary: comments
      sort: [eventdate, date, title]
      default:
        sort: eventdate
        order: desc
    fields:
      - { name: comments, label: Comments, type: string}
      - { name: eventdate, label: Event Date, type: date}
      - { name: title, label: Client Title, type: string, required: true }
      - { name: password, label: Password (optional), type: string }
      - { name: collection, label: Subtitle, type: string, required: true }
      - { name: heroBg, label: Hero Background Image, type: image, required: true }
      - { name: heroVideo, label: Hero Video URL (Big), type: string }
      - name: partners
        label: Partners
        type: object
        list: true
        fields: 
          - { name: name, label: Partner name, type: string, required: true}
          - { name: link, label: Partner link, type: string}
      - name: videos
        label: Videos
        type: object
        list: true
        fields:
          - { name: name, label: Video Name, type: string, required: true }
          - { name: url, label: Vimeo Video URL, type: string, required: true }
          - { name: poster, label: Video Poster, type: image, required: true }
          - { name: downloadUrl, label: Download Link, type: string, required: true }

      - name: seo
        label: OG Settings
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
          - { name: image, label: OG-image, type: image, description: Should be 1200x630px JPEG/PNG (under 5Mb) }

      - name: date
        type: date
        label: Created at
        readonly: true
